openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: https://music.gvsem.com/
paths:
  /:
    get:
      summary: Hello, world
      operationId: helloWorld
      responses:
        200:
          description: OK